/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UIs;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Dell
 */
public class LoadArchiveUI extends javax.swing.JFrame {
    
    private FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos de tipo TXT","txt","TXT");


    /**
     * Creates new form LoadArchiveUI
     */
    public LoadArchiveUI() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Title1 = new javax.swing.JLabel();
        Lab1 = new javax.swing.JLabel();
        Lab2 = new javax.swing.JLabel();
        CargarArchivoButt = new javax.swing.JButton();
        UsarArchivoButt = new javax.swing.JButton();
        Background1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 170, -1, -1));

        Title1.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        Title1.setForeground(new java.awt.Color(51, 51, 255));
        Title1.setText("Proyecto 1: Análisis de redes sociales");
        getContentPane().add(Title1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 500, 60));

        Lab1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Lab1.setForeground(new java.awt.Color(255, 255, 255));
        Lab1.setText("Por favor seleccione la opción");
        getContentPane().add(Lab1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 130, 290, 40));

        Lab2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Lab2.setForeground(new java.awt.Color(255, 255, 255));
        Lab2.setText("que desea realizar");
        getContentPane().add(Lab2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 170, 220, 40));

        CargarArchivoButt.setBackground(new java.awt.Color(102, 255, 255));
        CargarArchivoButt.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        CargarArchivoButt.setText("Cargar archivo");
        CargarArchivoButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargarArchivoButtActionPerformed(evt);
            }
        });
        getContentPane().add(CargarArchivoButt, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 240, 260, 70));

        UsarArchivoButt.setBackground(new java.awt.Color(102, 255, 255));
        UsarArchivoButt.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        UsarArchivoButt.setText("Usar archivo predeterminado");
        UsarArchivoButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsarArchivoButtActionPerformed(evt);
            }
        });
        getContentPane().add(UsarArchivoButt, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 350, 330, 80));

        Background1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UIs/fondo1.png"))); // NOI18N
        getContentPane().add(Background1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CargarArchivoButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarArchivoButtActionPerformed
        JFileChooser filechoose = new JFileChooser();
        filechoose.setFileFilter(filter);
        int opcion = filechoose.showOpenDialog(null);
        if(opcion == JFileChooser.APPROVE_OPTION){ 
            filechoose.showOpenDialog(null);
            File f = filechoose.getSelectedFile();
            String Filename = f.getAbsolutePath();
            JOptionPane.showMessageDialog(null, Filename);
            // colocamos la visualización de la ventana
            this.setVisible(false);
            VisualizeGraphUI ventanavisualize = new VisualizeGraphUI();
            ventanavisualize.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null, "El archivo que ha seleccionado es inválido");
            this.setVisible(true);
    }             
    }//GEN-LAST:event_CargarArchivoButtActionPerformed

    private void UsarArchivoButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsarArchivoButtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsarArchivoButtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoadArchiveUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoadArchiveUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoadArchiveUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoadArchiveUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoadArchiveUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background1;
    private javax.swing.JButton CargarArchivoButt;
    private javax.swing.JLabel Lab1;
    private javax.swing.JLabel Lab2;
    private javax.swing.JLabel Title1;
    private javax.swing.JButton UsarArchivoButt;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
