/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UIs;

import Graphs.Grafo;
import Graphs.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author Dell
 */
public class ModifyGraph extends javax.swing.JFrame {

    /**
     * Creates new form ModifyGraph
     */
    public ModifyGraph() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Title3 = new javax.swing.JLabel();
        Lab1 = new javax.swing.JLabel();
        Lab2 = new javax.swing.JLabel();
        Lab3 = new javax.swing.JLabel();
        Lab4 = new javax.swing.JLabel();
        AddUserTF = new javax.swing.JTextField();
        AddRelationTF = new javax.swing.JTextField();
        RemoveUserTF = new javax.swing.JTextField();
        RemoveRelationTF = new javax.swing.JTextField();
        AddUserButt = new javax.swing.JButton();
        AddRelationButt = new javax.swing.JButton();
        RemoveUserButt = new javax.swing.JButton();
        RemoveRelationButt = new javax.swing.JButton();
        BackToVisualizeButt = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, -1, -1));

        Title3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        Title3.setForeground(new java.awt.Color(255, 255, 255));
        Title3.setText("Modificación del grafo");
        getContentPane().add(Title3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 380, 50));

        Lab1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Lab1.setForeground(new java.awt.Color(255, 255, 255));
        Lab1.setText("Añadir usuario:");
        getContentPane().add(Lab1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 420, 40));

        Lab2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Lab2.setForeground(new java.awt.Color(255, 255, 255));
        Lab2.setText("Añadir relación:");
        getContentPane().add(Lab2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 360, 40));

        Lab3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Lab3.setForeground(new java.awt.Color(255, 255, 255));
        Lab3.setText("Eliminar usuario:");
        getContentPane().add(Lab3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 210, 40));

        Lab4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Lab4.setForeground(new java.awt.Color(255, 255, 255));
        Lab4.setText("Eliminar relación:");
        getContentPane().add(Lab4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 170, 40));
        getContentPane().add(AddUserTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 440, 50));
        getContentPane().add(AddRelationTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 440, 50));
        getContentPane().add(RemoveUserTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 440, 50));
        getContentPane().add(RemoveRelationTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 440, 50));

        AddUserButt.setBackground(new java.awt.Color(102, 255, 102));
        AddUserButt.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        AddUserButt.setText("Añadir");
        AddUserButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddUserButtActionPerformed(evt);
            }
        });
        getContentPane().add(AddUserButt, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, 150, 50));

        AddRelationButt.setBackground(new java.awt.Color(102, 255, 102));
        AddRelationButt.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        AddRelationButt.setText("Añadir");
        AddRelationButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddRelationButtActionPerformed(evt);
            }
        });
        getContentPane().add(AddRelationButt, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 210, 150, 50));

        RemoveUserButt.setBackground(new java.awt.Color(255, 0, 51));
        RemoveUserButt.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        RemoveUserButt.setText("Eliminar");
        RemoveUserButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveUserButtActionPerformed(evt);
            }
        });
        getContentPane().add(RemoveUserButt, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 300, 150, 50));

        RemoveRelationButt.setBackground(new java.awt.Color(255, 0, 51));
        RemoveRelationButt.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        RemoveRelationButt.setText("Eliminar");
        RemoveRelationButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveRelationButtActionPerformed(evt);
            }
        });
        getContentPane().add(RemoveRelationButt, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 400, 150, 50));

        BackToVisualizeButt.setBackground(new java.awt.Color(102, 255, 255));
        BackToVisualizeButt.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        BackToVisualizeButt.setText("Volver a visualización");
        BackToVisualizeButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackToVisualizeButtActionPerformed(evt);
            }
        });
        getContentPane().add(BackToVisualizeButt, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 220, 250, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UIs/fondoGrafosOperations.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddUserButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddUserButtActionPerformed
        String user;
        try{
            user = AddUserTF.getText();
            Grafo adduser = new Grafo();
            adduser.agregarVertice(user);
            AddUserTF.setText(" ");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "El input no es válido");
        }
    }//GEN-LAST:event_AddUserButtActionPerformed

    private void AddRelationButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddRelationButtActionPerformed
        String relation;
        try{
            relation = AddRelationTF.getText();
            Grafo addrelation = new Grafo();
            addrelation.agregarRelacion(relation, relation);
            AddUserTF.setText(" ");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "El input no es válido");
        }
    }//GEN-LAST:event_AddRelationButtActionPerformed

    private void RemoveUserButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveUserButtActionPerformed
        //
    }//GEN-LAST:event_RemoveUserButtActionPerformed

    private void RemoveRelationButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveRelationButtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RemoveRelationButtActionPerformed

    private void BackToVisualizeButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackToVisualizeButtActionPerformed
        this.setVisible(false);
        VisualizeGraphUI ventanaVisu = new VisualizeGraphUI();
        ventanaVisu.setVisible(true);
    }//GEN-LAST:event_BackToVisualizeButtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModifyGraph.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModifyGraph.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModifyGraph.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModifyGraph.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModifyGraph().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddRelationButt;
    private javax.swing.JTextField AddRelationTF;
    private javax.swing.JButton AddUserButt;
    private javax.swing.JTextField AddUserTF;
    private javax.swing.JButton BackToVisualizeButt;
    private javax.swing.JLabel Lab1;
    private javax.swing.JLabel Lab2;
    private javax.swing.JLabel Lab3;
    private javax.swing.JLabel Lab4;
    private javax.swing.JButton RemoveRelationButt;
    private javax.swing.JTextField RemoveRelationTF;
    private javax.swing.JButton RemoveUserButt;
    private javax.swing.JTextField RemoveUserTF;
    private javax.swing.JLabel Title3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
