/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UIs;

import UIs.ViewGraphs;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Dell
 */
public class LoadArchivesUI extends javax.swing.JFrame {
    
    private FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos de tipo TXT","txt","TXT");


    /**
     * Creates new form LoadArchivesUI
     */
    public LoadArchivesUI() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Title1 = new javax.swing.JLabel();
        lab1 = new javax.swing.JLabel();
        lab2 = new javax.swing.JLabel();
        CargarArchivoButt = new javax.swing.JButton();
        UtilizarArchivoButt = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, -1, -1));

        Title1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        Title1.setForeground(new java.awt.Color(51, 51, 255));
        Title1.setText("Proyecto 1: Análisis de redes sociales");
        getContentPane().add(Title1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 500, 60));

        lab1.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        lab1.setForeground(new java.awt.Color(255, 255, 255));
        lab1.setText("Por favor seleccione la");
        getContentPane().add(lab1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 100, 240, 60));

        lab2.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        lab2.setForeground(new java.awt.Color(255, 255, 255));
        lab2.setText("opción que desea realizar");
        getContentPane().add(lab2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 130, 270, 60));

        CargarArchivoButt.setBackground(new java.awt.Color(102, 255, 255));
        CargarArchivoButt.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        CargarArchivoButt.setText("Cargar archivo");
        CargarArchivoButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargarArchivoButtActionPerformed(evt);
            }
        });
        getContentPane().add(CargarArchivoButt, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 230, 210, 60));

        UtilizarArchivoButt.setBackground(new java.awt.Color(102, 255, 255));
        UtilizarArchivoButt.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        UtilizarArchivoButt.setText("Utilizar archivo por defecto");
        UtilizarArchivoButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UtilizarArchivoButtActionPerformed(evt);
            }
        });
        getContentPane().add(UtilizarArchivoButt, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 340, 320, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UIs/fondo1.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UtilizarArchivoButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UtilizarArchivoButtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UtilizarArchivoButtActionPerformed

    private void CargarArchivoButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarArchivoButtActionPerformed
        JFileChooser filechoose = new JFileChooser();
        filechoose.setFileFilter(filter);
        int opcion = filechoose.showOpenDialog(null);
        if(opcion == JFileChooser.APPROVE_OPTION){ 
            filechoose.showOpenDialog(null);
            File f = filechoose.getSelectedFile();
            String Filename = f.getAbsolutePath();
            JOptionPane.showMessageDialog(null, Filename);
            // colocamos la visualización de la ventana
            this.setVisible(false);
            ViewGraphs ventanaview = new ViewGraphs();
            ventanaview.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null, "El archivo que ha seleccionado es inválido");
            this.setVisible(true);
    }                                                 
    }//GEN-LAST:event_CargarArchivoButtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoadArchivesUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoadArchivesUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoadArchivesUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoadArchivesUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoadArchivesUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CargarArchivoButt;
    private javax.swing.JLabel Title1;
    private javax.swing.JButton UtilizarArchivoButt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lab1;
    private javax.swing.JLabel lab2;
    // End of variables declaration//GEN-END:variables
}
