/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package classes;

/**
 *
 * @author Dell
 */
public class DataInterfaz extends javax.swing.JFrame {

    /**
     * Creates new form DataInterfaz
     */
    public DataInterfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        TituloGrafo = new javax.swing.JLabel();
        VerGrafo = new javax.swing.JButton();
        InstructionsGrafo = new javax.swing.JLabel();
        CFCGrafo = new javax.swing.JButton();
        ModificarGrafo = new javax.swing.JButton();
        DataBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, -1, -1));

        TituloGrafo.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        TituloGrafo.setForeground(new java.awt.Color(255, 255, 255));
        TituloGrafo.setText("Grafo");
        getContentPane().add(TituloGrafo, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 80, 80));

        VerGrafo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        VerGrafo.setText("Visualizar grafo");
        VerGrafo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerGrafoActionPerformed(evt);
            }
        });
        getContentPane().add(VerGrafo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 180, 70));

        InstructionsGrafo.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        InstructionsGrafo.setForeground(new java.awt.Color(255, 255, 255));
        InstructionsGrafo.setText("Por favor seleccione la opción que desea realizar");
        getContentPane().add(InstructionsGrafo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, 380, 50));

        CFCGrafo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        CFCGrafo.setText("Componentes Fuertemente conectados");
        getContentPane().add(CFCGrafo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, 310, 70));

        ModificarGrafo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ModificarGrafo.setText("Modificación del grafo");
        ModificarGrafo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarGrafoActionPerformed(evt);
            }
        });
        getContentPane().add(ModificarGrafo, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 270, 220, 70));

        DataBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classes/FondoGrafos.png"))); // NOI18N
        getContentPane().add(DataBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ModificarGrafoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarGrafoActionPerformed
        this.setVisible(false);
        ModificarGrafosInterfaz ventanamod = new ModificarGrafosInterfaz();
        ventanamod.setVisible(true);
    }//GEN-LAST:event_ModificarGrafoActionPerformed

    private void VerGrafoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerGrafoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VerGrafoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataInterfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CFCGrafo;
    private javax.swing.JLabel DataBackground;
    private javax.swing.JLabel InstructionsGrafo;
    private javax.swing.JButton ModificarGrafo;
    private javax.swing.JLabel TituloGrafo;
    private javax.swing.JButton VerGrafo;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
